theme: minima

title: Martin's Blog
author: malo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the greatest Blog ever.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  malo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
